### ISSUE TITLE
Modem stuck after dropped call

### ISSUE THREAD

**Issue by maxxer** [hehol/t38modem#2] opened 2014-10-20 11:20 UTC
I'm having this issue with 2.0.0, but I tried now upgrading to 3.x and it's still present. I'm running Hyla 6.0.5. When I make a test call with my phone and hang it up few seconds later the modem remains stuck in "Receiving facsimile" even if the remote end has dropped the call. Running t38modem in debug outputs the following:

```
Opal Garba...3d74d2c700 OpalCon Connection Call[Cd2718a7b2]-EP<sip>[e28688e7-b756-e411-8677-005056a6e2a5] destroyed.
Housekeepe...3d5b96b700 ModemEngineBody::OnTimerCallback stSendAckWait Timeout 1
Opal Garba...3d74d2c700 Call    Destroyed Call[Cd2718a7b2]
Housekeepe...c80ffbe700 ModemEngineBody::OnTimerCallback stSendAckWait Timeout 1
```

and then the last line is repeated forever.

Here's the full log of the dropped call (with 2.x):
https://dl.dropboxusercontent.com/u/706934/t38modem.log.gz

```
$ t38modem --version
T38Modem Version 3.11.0
 (OPAL-3.10.10/3.10.10 (svn:29150), PTLIB-2.10.10/2.10.10 (svn:29149)) by Frolov,Holtschneider,Davidson on Unix Linux (3.2.0-29-generic-x86_64)
```

**Comment by Wimdv** [comment] 2015-01-23 08:37
Maxxer,

I have the same issue,  Hylafax version 6.0.6-5, T38modem version   2.0.0
 (OPAL-3.10.10/3.10.10 (svn:29150), PTLIB-2.10.10/2.10.10 (svn:29149)) by Vyacheslav Frolov on Unix Linux (3.2.0-4-amd64-x86_64)

Did you find a cause and/or fix for this?
I have other instances of T38modem + hylafax running that seem identical to me where it works fine.

**Comment by maxxer** [comment] 2015-01-23 08:50
Sadly not. Like for you I found a solution that has been working for some time, but then after a reboot it stopped and I never managed it back to service. It highly depends on ptlib/opal versions, so check you're using the exact same versions on all installations. And in case you find a good combination please share. In the past [I thought](https://sourceforge.net/p/opalvoip/mailman/message/32975077/) 3.10.3 were good with this source, but as I told you before it's not running anymore, so if you make it working please share. From the opal mailing list @hehol said to be working on [a new branch](https://github.com/hehol/t38modem/commits/opal314) to update t38modem, in order to make it compatible with latest opal sources.

**Comment by wuschi** [comment] 2015-01-30 14:03
Any News on this issue? I am having the same problems with the t38modem 3.11.0 / Hylafax 6.0.6-5

T38Modem Version 3.11.0
 (OPAL-3.10.10/3.10.10 (svn:29150), PTLIB-2.10.10/2.10.10 (svn:29149)) by Frolov,Holtschneider,Davidson on Unix Linux (3.12-1-amd64-x86_64)

The problem is absolutely reproducable on one of our machines: Just Dial in to the t38modem using a telephone (_not_ a fax device) and hangup when the fax carrier signal can be heard.

faxstat -l lists the modem as "Receiving facsimile", and the t38modem stays in cstReleasing afterwards.

I uploaded a detailled trace to http://www.filedropper.com/t38modem0 in case anyone wants to have a look at the problem.

**Comment by wuschi** [comment] 2015-02-02 12:51
Update: This seems to be related to either opal > 3.10.4 or the latest merges from Pete Davidsons branch.

I unapplied those changes and compiled against opal 3.10.4 / ptlib 2.10.4.
The problem doesn't show up with this combination.

**Comment by hehol** [comment] 2015-02-02 13:38
Use OPAL > 3.10.3 at you own risk. t38modem is not designed to be used with newer OPAL releases.

I'm working on a version of t38modem that works with more modern OPAL releases.

**Comment by hehol** [comment] 2024-02-02 11:30
I will close the issue. T38Modem 4.6.0 supports OPAL up to version 3.18.2.

**Closed by hehol** 2024-02-02 11:30 UTC
